### ISSUE TITLE
Support phantomjs 2.0

### ISSUE THREAD

**Issue by fifigyuri** [colszowka/phantomjs-gem#54]
I tried to upgrade to phantomJs 2.0 here https://github.com/netronixgroup/phantomjs-gem/tree/upgrade-to-2.0.0.

Several specs fail, I'm not familiar with the codebase. Can you help to upgrade it to support 2.0?

**Comment by mtyeh411** [comment]
+1

**Comment by ponchik** [comment]
+1

**Comment by jeffnappi** [comment]
+1

**Comment by mikeb-iacquire** [comment]
+1

**Comment by nanernunes** [comment]
+1

**Comment by jeffnappi** [comment]
Looks like this will have to wait until PhantomJS themselves get the static Linux binaries working. See https://github.com/ariya/phantomjs/issues/12948

**Comment by swistaczek** [comment]
+1

**Comment by karlingen** [comment]
+1

**Comment by mgrachev** [comment]
+1

**Comment by edenvicary** [comment]
:+1:

**Comment by dmitry** [comment]
https://github.com/gitromand/phantomjs/releases - available phantomjs-2.0.1-development-linux-x86_64.zip

**Comment by betelgeuse** [comment]
@dmitry I don't think this gem should use binaries not sanctioned by upstream (you linked to a forked repo).

**Comment by dmitry** [comment]
@betelgeuse thank you for noticing that. Lets wait till the upstream binaries will appear.

**Comment by meghan-mcqueeney** [comment]
+1

**Comment by dmitry** [comment]
Guys, just to understand: what means `+1`?

Is it's something like:
> please implement, but I cannot help you anyhow"

Or there are some other meaning of such comments?

**Comment by betelgeuse** [comment]
@dmitry It's like Facebook like or the vote functionality in bugzilla. Since Github does not have native support for it, many people have taken to using +1 to signal importance. I am not sure what my personal opinion on such comments is given the current Github feature set.

**Comment by kuraga** [comment]
+1

**Comment by pivotal-rivals** [comment]
The main PhantomJS repo builds its binaries from the [deploy page](https://github.com/ariya/phantomjs/tree/master/deploy) page for both Linux and Mac OSX. They have prebuilt it for Mac on their [download page](http://phantomjs.org/download.html). For Linux, but have one remaining [issue 12948](https://github.com/ariya/phantomjs/issues/12948).

**Comment by montulli** [comment]
+1

**Comment by sashee** [comment]
The official 2.1.1 version is out, with official Linux binaries.

**Comment by colszowka** [comment]
Finally, excellent! Would you mind sending in a PR with the updated urls?





On Mon, Jan 25, 2016 at 1:13 PM -0800, "Tamás Sallai" <notifications@github.com> wrote:












The official 2.1.1 version is out, with official Linux binaries.

**Comment by sashee** [comment]
Yep, just opened #66 .

**Comment by BrianHawley** [comment]
Please close this in favor of #66.

**Comment by mgrachev** [comment]
We need a new release 2.1.1.0 on rubygems

**Comment by colszowka** [comment]
@mgrachev The build on travis CI was failing, it is now fixed with #68 - I will ship the new release in a few minutes.

**Comment by mgrachev** [comment]
@colszowka Thanks!
