### ISSUE TITLE
PhantomJS not detected on Travis

### ISSUE THREAD

**Issue by seanlinsley** [colszowka/phantomjs-gem#79]
[Travis has PhantomJS preinstalled](https://docs.travis-ci.com/user/gui-and-headless-browsers#using-phantomjs), but [this gem doesn't seem to detect it](https://travis-ci.org/activeadmin/activeadmin/jobs/118716519#L361).

The Travis documentation has this note:

> (available in PATH as phantomjs; don’t rely on the exact location)

So perhaps this gem is looking in the wrong location? This is where it's currently looking:

```
/home/travis/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs
```

**Comment by twalpole** [comment]
Travis has phantomjs 1.9.8 preinstalled -- you really don't want to be using that anymore - and this gem is looking for 2.1.1.  If you really want to use the travis installed version then you should be using the phantomjs gem v 1.9.8.0

**Comment by seanlinsley** [comment]
I don't have a need for a particular version. I only created this ticket under the assumption that this gem would never use the version that Travis provides. If that's not true, and it'll start using the Travis version once Travis upgrades the version they provide, this ticket can be closed.

**Comment by andresilveirah** [comment]
@seanlinsley do you still have this issue? For me, it correctly installs and locates the latest version (2.1.1) of phantomjs. I notice the issue is a bit outdated hence the question.

**Comment by seanlinsley** [comment]
No, this is no longer an issue.
